model:
  base_learning_rate: 1e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
#    ckpt_path: /home/zhanglu/ldm/logs/2024-08-16T17-42-47_cin-ldm-vq-f8-3d/checkpoints/last.ckpt   # shell
#    ckpt_path: /home/zhanglu/ldm/logs/2024-08-29T15-22-19_cin-ldm-vq-f8-3d/checkpoints/epoch=000020.ckpt  # shell truss
    ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-11-18T10-13-53_cin-ldm-vq-f8-3d-5l/checkpoints/last.ckpt
    scale_factor: 0.2
    parameterization: x0
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: sdf
    cond_stage_key: C
    image_size: 5
    channels: 4
    z_norm: false
    cond_stage_trainable: true
    cond_stage_copy: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 5
        in_channels: 4
        out_channels: 4
        model_channels: 128
        dims: 3
        attention_resolutions:
        #note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 32 for f8
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
          projection: True
          embed_dim: 4
#          ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-08-16T16-14-09_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt  # shell
#          ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-08-25T21-14-43_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt  # shell truss
#          ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-09-16T21-34-02_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt # shell truss log
#          ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-10-23T14-57-50_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt # shell truss log sigma_C=0.03
#          ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-10-29T14-54-47_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt # shell truss log sigma_C=1.0
          ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-11-17T01-19-36_autoencoder_kl_32x32x4_3d_5l/checkpoints/epoch=000001.ckpt # shell truss log sigma_C=0.06
          lossconfig:
            target: ldm.modules.losses.LPIPSWithDiscriminator
            params:
              is_3d: True
              disc_start: 50001
              kl_weight: 0.000001
              disc_weight: 0.5
              disc_in_channels: 1

          ddconfig:
            3d: True
            double_z: True
            z_channels: 4
            resolution: 80
            in_channels: 1
            out_ch: 1
            ch: 64
            ch_mult: [ 1,2,4,4,8 ]  # num_down = len(ch_mult)-1
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.0

          projection_s_config:
            in_dim: 4
            embed_dim: 48
            res_dim: 512

          encoder_p_config:
            embed_dim: 512
            res_dim: 512
            key: C
            sigma_c: 0.06  # 0.03
            sigma_vf: 0.6  #0.6
            range_c: [ -8.0, 8.0 ]
            range_vf: [ -0.2, 0.6 ]
            vf: False

          decoder_p_config:
            in_dim: 512
            vf: False

    cond_stage_config:
      target: ldm.modules.encoders.modules.CEmbedder_vf    #CEmbedder
      params:
        embed_dim: 512
        res_dim: 512
        key: C
        sigma_c: 0.06
        sigma_vf: 0.6
        range_c: [-8.0, 8.0]
        range_vf: [-0.2, 0.6]
        vf: False

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.microstructure.MSTrain
      params:
        size: 256
        degradation: pil_nearest
        mask: True
        norm: False
        log: True
        c_vf: False
        c_noise: 0.02
        flag_path: "clean_in_stage1_thresh_0.3_vf_0.2_0.25"  #"clean_in_stage1_thresh_0.1_vf_0.25_0.32"
    validation:
      target: ldm.data.microstructure.MSValidation
      params:
        size: 256
        degradation: pil_nearest
        mask: True
        norm: False
        log: True
        c_vf: False
        c_noise: 0.0
        flag_path: "clean_in_stage1_thresh_0.3_vf_0.2_0.25"  #"clean_in_stage1_thresh_0.1_vf_0.25_0.32"


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1500
        max_images: 4
        increase_log_steps: False

  trainer:
    benchmark: True