model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
#    ckpt_path: /home/zhanglu/ldm/logs/2024-07-30T14-28-20_cin-ldm-vq-f8-3d/checkpoints/epoch=000022.ckpt  # great performance bad C matrix
#    ckpt_path: /home/zhanglu/ldm/logs/2024-07-31T17-02-04_cin-ldm-vq-f8-3d/checkpoints/epoch=000400.ckpt  #  great performance
#    ckpt_path: /home/zhanglu/ldm/logs/2024-08-09T13-38-18_cin-ldm-vq-f8-vit-3d/checkpoints/epoch=000035.ckpt
    parameterization: x0
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: sdf
    cond_stage_key: C
    image_size: 10
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.uvit.UViT
      params:
        img_size: 10
        in_chans: 4
        num_clip_token: 36
        patch_size: 2  # 2 5
        embed_dim: 768 # 768  1536
        clip_dim: 512
        conv: False
        is_3d: True
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
          embed_dim: 4
#          ckpt_path: /home/zhanglu/ldm/logs/2024-07-30T09-32-18_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt     #  great structure, poor C matrix
#          ckpt_path: /home/zhanglu/ldm/logs/2024-07-31T14-48-05_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt     #  great performance, great C matrix 20%~30%
#          ckpt_path: /home/zhanglu/ldm/logs/2024-08-03T17-25-37_autoencoder_kl_32x32x4_3d/checkpoints/epoch=000032.ckpt
#          ckpt_path: "/home/zhanglu/ldm/logs/2024-08-02T15-26-59_autoencoder_kl_32x32x4_3d/checkpoints/epoch=000072.ckpt"
          ckpt_path: /home/zhanglu/ldm/logs/2024-08-06T15-14-27_autoencoder_kl_32x32x4_3d/checkpoints/epoch=000090.ckpt
          lossconfig:
            target: ldm.modules.losses.LPIPSWithDiscriminator
            params:
              is_3d: True
              disc_start: 50001
              kl_weight: 0.000001
              disc_weight: 0.5
              disc_in_channels: 1
          ddconfig:
            3d: True
            double_z: True
            z_channels: 4
            resolution: 80
            in_channels: 1
            out_ch: 1
            ch: 64
            ch_mult: [ 1,2,4,4 ]  # num_down = len(ch_mult)-1
            num_res_blocks: 2
            attn_resolutions: [ ]
            dropout: 0.0
    cond_stage_config:
      target: ldm.modules.encoders.modules.CEmbedder_L
      params:
        embed_dim: 512
        key: C

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.microstructure.MSTrain
      params:
        size: 256
        degradation: pil_nearest
    validation:
      target: ldm.data.microstructure.MSValidation
      params:
        size: 256
        degradation: pil_nearest


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 500
        max_images: 4
        increase_log_steps: False

  trainer:
    benchmark: True