model:
  base_learning_rate: 4.5e-6 #4.5e-6
  target: ldm.models.autoencoder.AutoencoderKL
  params:
#    ckpt_path: /home/zhanglu/ldm/logs/2024-08-16T14-36-32_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt
#    ckpt_path : /home/zhanglu/ldm/logs/2024-08-23T10-44-51_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt
#    ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-09-16T14-10-37_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt
#    ckpt_path : /mnt/zhanglu/inverse/ldm/logs/2024-10-10T11-42-31_autoencoder_kl_32x32x4_3d/checkpoints/last.ckpt
    ckpt_path: /mnt/zhanglu/inverse/ldm/logs/2024-11-15T11-04-43_autoencoder_kl_32x32x4_3d_5l/checkpoints/last.ckpt
    monitor: "val/rec_loss"
    embed_dim: 4
    image_key: "sdf"
    projection: True
    gan_inter: True
    z_norm: True
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 0
        kl_weight: 0.00005
        disc_weight: 0.5
        perceptual_weight: 0.0
        disc_in_channels: 1
        is_3d: True

    ddconfig:
      3d: True
      double_z: True
      z_channels: 4
      resolution: 80
      in_channels: 1
      out_ch: 1
      ch: 64
      ch_mult: [ 1,2,4,4,8]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [ ]
      dropout: 0.0

    projection_s_config:
      in_dim: 4
      embed_dim: 48
      res_dim: 512
      resolution: 5

    encoder_p_config:
      embed_dim: 512
      res_dim: 512
      key: C
      sigma_c: 0.06  # 0.03
      sigma_vf: 0.6  #0.6
      range_c: [ -8.0, 8.0 ]
      range_vf: [ -0.2, 0.6 ]
      vf: False

    decoder_p_config:
      in_dim: 512
      vf: False


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 3
    num_workers: 0
    wrap: false
    train:
      target: ldm.data.microstructure.MSTrain
      params:
        size: 256
        degradation: pil_nearest
        mask: False
        norm: False
        log: True
        c_vf: False
        flag_path: "clean_in_stage1_thresh_0.3_vf_0.2_0.25"  #"clean_in_stage1_thresh_0.1_vf_0.25_0.32"  "st_all_clean"  "clean_in_stage1_thresh_0.3_vf_0.2_0.25"
    validation:
      target: ldm.data.microstructure.MSValidation
      params:
        size: 256
        degradation: pil_nearest
        mask: False
        norm: False
        log: True
        c_vf: False
        flag_path: "clean_in_stage1_thresh_0.3_vf_0.2_0.25"  #"clean_in_stage1_thresh_0.1_vf_0.25_0.32" "st_all_clean"  "clean_in_stage1_thresh_0.3_vf_0.2_0.25"

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
